# Generated by Django 3.0.5 on 2020-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='flowchartterm',
            name='batch',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
