# Generated by Django 3.0.5 on 2020-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200414_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
