# Generated by Django 3.0.5 on 2020-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
