# Generated by Django 3.0.5 on 2020-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200407_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='flowchart',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
